/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ashis
 */
import java.awt.Image;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    
    private void scaleImage(String location, JLabel jLabelLogo){
        ImageIcon icon = new ImageIcon("/Images/Northeastern_Wordmark.svg.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jLabelLogo.setIcon(scaledIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernamelbl = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        rolelbl = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        roleTxt = new javax.swing.JComboBox<>();
        submitBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        Logintxt = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        usernamelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernamelbl.setForeground(new java.awt.Color(153, 0, 51));
        usernamelbl.setText("Username:");
        jPanel1.add(usernamelbl);
        usernamelbl.setBounds(160, 250, 90, 32);

        passwordlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordlbl.setForeground(new java.awt.Color(153, 0, 51));
        passwordlbl.setText("Password:");
        jPanel1.add(passwordlbl);
        passwordlbl.setBounds(160, 300, 77, 27);

        rolelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rolelbl.setForeground(new java.awt.Color(153, 0, 51));
        rolelbl.setText("Role:");
        jPanel1.add(rolelbl);
        rolelbl.setBounds(160, 340, 63, 20);

        usernameTxt.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(usernameTxt);
        usernameTxt.setBounds(310, 250, 199, 22);

        roleTxt.setBackground(new java.awt.Color(204, 204, 204));
        roleTxt.setForeground(new java.awt.Color(153, 0, 51));
        roleTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher", "Police", "BankEmployee", " " }));
        jPanel1.add(roleTxt);
        roleTxt.setBounds(310, 340, 199, 22);

        submitBtn.setBackground(new java.awt.Color(153, 0, 51));
        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn);
        submitBtn.setBounds(310, 400, 150, 40);

        passwordTxt.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(passwordTxt);
        passwordTxt.setBounds(310, 300, 199, 22);

        Logintxt.setBackground(new java.awt.Color(255, 0, 0));
        Logintxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logintxt.setForeground(new java.awt.Color(153, 0, 0));
        Logintxt.setText("LOGIN");
        jPanel1.add(Logintxt);
        Logintxt.setBounds(330, 170, 60, 30);
        jPanel1.add(jLabelLogo);
        jLabelLogo.setBounds(100, 30, 510, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String role = roleTxt.getSelectedItem().toString();
        String username = usernameTxt.getText();
        String password = passwordTxt.getText();
        if(usernameTxt.getText().isEmpty()|| passwordTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Plz Enter Details!");

        } else{

            try{
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user@1234");

                System.out.println("connection open");
                Statement statement = connection.createStatement();
                ResultSet resultset = statement.executeQuery
                ("SELECT * FROM universitysystem.login where role ='" + role + "' and username ='" + username + "' and password = '" + password + "'");

//                if("Student".equals(role) && resultset.next()){
//                    Student s = new Student();
//                    setVisible(false);
//                    s.show();
//                }else if("Teacher".equals(role) && resultset.next()){
//                     Teacher t = new Teacher();
//                    setVisible(false);
//                    t.show();
//                }else 
                    
                if("Police".equals(role) && resultset.next()){
                    Police p = new Police();
                    setVisible(false);
                    p.show();
                }

                else{
                    JOptionPane.showMessageDialog(null,"Invalid Credentials!");
                }
                connection.close();
                System.out.println("connection close");
            }catch(SQLException e){

    }//GEN-LAST:event_submitBtnActionPerformed
        
        }
    }
    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logintxt;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JComboBox<String> roleTxt;
    private javax.swing.JLabel rolelbl;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JLabel usernamelbl;
    // End of variables declaration//GEN-END:variables
}
